### ISSUE TITLE
Generating the FIREBASE_TOKEN

### ISSUE THREAD

**Issue by shalomvolchok** [jackyzhen/firebase-lambda-backup#1]
Nice lambda function, thanks for sharing. I've been struggling to see how to generate a token that works for the Firebase rest api. Doesn't seem to be well documented, or I'm totally missing it. Would you mind sharing how you create the FIREBASE_TOKEN?

**Comment by tomarrell** [comment]
If you login to firebase and go through the settings of your database by clicking the gear icon next to the Overview button, you should see on the far right "Service Accounts."

Alternatively you can follow this link https://console.firebase.google.com/project/<YOUR_FIREBASE_NAME>/settings/database

Under Firebase Secrets, click "Add Secrets" and copy the secret to be used in your application.

**Comment by shalomvolchok** [comment]
Great! I couldn't find that documented anywhere and it does indeed work. Thanks!
